### ISSUE TITLE
bs-share-buttons returns "Array"

### ISSUE THREAD

**Issue by gAlleb** [bootscore/bs-share-buttons#3]
### Describe the bug

I'm not sure is it just me doing something wrong or not. Recently I started to see `Array` word just before `bs-share-buttons` block)

<img width="500" alt="image" src="https://github.com/user-attachments/assets/0cdc4bf7-11cc-42b0-993e-35d26015f554">

```html
<div class="sharebuttonsblock">
 <?php echo do_shortcode("[bs-share-buttons]"); ?>
</div>
```

`bootScore 5.3.4`
`WP 6.6.1`

**Comment by crftwrk** [comment]
Here is a rough fix for that issue. Please uninstall old version first before uploading the patch.

https://github.com/bootscore/bs-share-buttons/releases/download/v1.0.1/bs-share-buttons.zip

Note that this plugin has reached its end of life (EOL) and will no longer receive updates.
